url=https://www.jotform.com/form-templates/exam-registration-form
fName=//*[@id="first_9"]
lName=//*[@id="last_9"]
stdRno=input_10
regCrs=//*[@id="input_3"]
examStart=//*[@id="lite_mode_11"]
examEnd=//*[@id="lite_mode_12"]
comment=//*[@id="input_8"]
submit=//*[@id="input_16"]
