url=https://register.rediff.com/register/register.php?FormName=user_details
fullName=input[name^="name"]
rediffID=input[name^="login"]
chkavailable=input[name^="btnchkavail"]
pass=newpasswd
repass=newpasswd1
day=select[name^="DOB_Day"]
month=select[name^="DOB_Month"]
year=select[name^="DOB_Year"]
rdbtnmale=/html/body/div[2]/div[2]/form/div/div[9]/div/label[1]/input
rdbtnfemale=/html/body/div[2]/div[2]/form/div/div[9]/div/label[2]/input